---
- name: Create certificates directory for config
  ansible.builtin.file:
    path: /etc/elasticsearch/certs
    state: directory

- name: Copy certificates and keys to remote_hosts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/elasticsearch/certs
  with_items: 
    - /tmp/elastic-certs/ca.crt
    - /tmp/elastic-certs/{{ inventory_hostname }}.crt
    - /tmp/elastic-certs/{{ inventory_hostname }}.key
  notify: Restarting elasticsearch service